---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: check-json
          - id: check-executables-have-shebangs
          - id: check-shebang-scripts-are-executable
#     - id: no-commit-to-branch # both main and master are protected by default
          - id: detect-private-key
          - id: detect-aws-credentials
            args:
                - --allow-missing-credentials

    - repo: https://github.com/ansible/ansible-lint.git
      rev: v4.2.0
      hooks:
          - id: ansible-lint
            files: \.(yaml|yml)$

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: markdownlint
    - repo: https://github.com/markdownlint/markdownlint
      rev: v0.12.0
      hooks:
          - id: markdownlint
